In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
# feed forward netwrok

In [2]:
class FeedForward(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(FeedForward, self).__init__()#assigmnet
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)
         
    def forward(self,x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        
        return out

In [3]:
input_size = 4
hidden_size = 5
output_size = 3

In [4]:
model = FeedForward(input_size, hidden_size, output_size)

In [5]:
model

FeedForward(
  (fc1): Linear(in_features=4, out_features=5, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=5, out_features=3, bias=True)
)

In [ ]:
# loss function and optimizer

In [25]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr = 0.001)

In [26]:
model

FeedForward(
  (fc1): Linear(in_features=4, out_features=5, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=5, out_features=3, bias=True)
)

In [ ]:
# training

In [19]:
input_data = torch.tensor([[1.0,2.0,3.0,4.0], [4.0, 5.0,6.0,7.0]])

In [20]:
input_data

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])

In [21]:
target = torch.tensor([0,2])

In [22]:
target

tensor([0, 2])

In [23]:
# feed forward
output = model(input_data)
output

tensor([[ 0.2476,  0.2154, -0.0512],
        [ 0.5629,  0.5771,  0.1112]], grad_fn=<AddmmBackward>)

In [30]:
# back propagation
num_epochs = 1000

for epoch in range(num_epochs):
    output = model(input_data)
    
    loss = criterion(output, target)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch+1) % 100 == 0:
        print(f"epoch [{epoch+1}/{num_epochs}], loss: {loss.item(): .4f}")

epoch [100/1000], loss:  0.5972
epoch [200/1000], loss:  0.5919
epoch [300/1000], loss:  0.5869
epoch [400/1000], loss:  0.5819
epoch [500/1000], loss:  0.5770
epoch [600/1000], loss:  0.5723
epoch [700/1000], loss:  0.5676
epoch [800/1000], loss:  0.5629
epoch [900/1000], loss:  0.5584
epoch [1000/1000], loss:  0.5539


In [ ]:
model

In [28]:
with torch.no_grad():
    output = model(input_data)
    print(output)
#     print("----------")
#     print(torch.max(output.data, 1))
#     print()
    _, predicted = torch.max(output.data, 1)
    print(f"predcited class is: {predicted.numpy()}")
    print(f"actual  class is: {target.numpy()}")
    

tensor([[ 0.9043, -0.6774,  1.2467],
        [ 1.7523, -0.7300,  2.5345]])
predcited class is: [2 2]
actual  class is: [0 2]


In [ ]:
predicted